#define VERSION_STRING "@VERSION@"
#define VERSION_RC @VERSION_Y@,@VERSION_M@,@VERSION_D@,@VERSION_B@
#define SKYM_COMPILER "@SKYM_COMPILER@"
#define SKYM_ARCHITECTURE "@SKYM_ARCHITECTURE@"
#define SKYM_BUILD_TYPE "@SKYM_BUILD_TYPE@"
#define SKYM_KEY_ROOT "Software\\SKYM"
#define SKYM_KEY_ROOT_W L"Software\\SKYM"
