#define VERSION_STRING "@VERSION@"
#define VERSION_RC @VERSION_Y@,@VERSION_M@,@VERSION_D@,@VERSION_B@
#define SARU_COMPILER "@SARU_COMPILER@"
#define SARU_ARCHITECTURE "@SARU_ARCHITECTURE@"
#define SARU_BUILD_TYPE "@SARU_BUILD_TYPE@"
#define SARU_KEY_ROOT "Software\\SARU"
#define SARU_KEY_ROOT_W L"Software\\SARU"
